Approver Guide Documentation
LizardByte/ThemerrDB pull request #4373
Opened 2024-06-05 05:09 UTC by jjnether

## Description
Add a page for approvers to the docs.

### Screenshot

### Issues Fixed or Closed

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency update (updates to dependencies)
- [x] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

## Branch Updates
LizardByte requires that branches be up-to-date before merging. This means that after any PR is merged, this branch
must be updated before it can be merged. You must also
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I want maintainers to keep my branch updated

2024-06-07 20:08 UTC, ReenigneArcher requested changes

2024-06-07 20:08 UTC, ReenigneArcher commented on docs/Approver_Guide
> +> Try to avoid approving any themes when a scheduled update is running. You can check for that [here](https://github.com/LizardByte/ThemerrDB/actions/workflows/update-pages.yml?query=event%3Aschedule
The time could be updated to be 12:00 UTC, instead of "the morning..."

2024-06-07 20:08 UTC, ReenigneArcher commented on docs/Approver_Guide
> +- A bot workflow to begin adding a theme can be manually initiated by adding the `approve-theme` label.
```suggestion
- A bot workflow to begin adding a theme can be manually initiated by adding the `approve-queue` label.
```

Let's list this as the queue label, as it's safer.

2024-06-07 20:08 UTC, ReenigneArcher commented on docs/Approver_Guide
> +> `request-theme` and `approve-theme` labels should typically not need to be manually added, but they are helpful for troubleshooting
```suggestion
> These labels should typically not need to be manually added, but they are helpful for troubleshooting
```

2024-06-07 20:08 UTC, ReenigneArcher commented on docs/images/do_not_add.diff
Should we add a different directory for these diffs, since they are not images? Maybe `references` or `samples`?

2024-06-07 20:08 UTC, ReenigneArcher commented on docs/images/do_not_add.diff
> + }
```suggestion
 }

```

Just add a blank line at the end.

2024-06-07 20:08 UTC, ReenigneArcher commented on docs/images/okay.diff
> +\ No newline at end of file
```suggestion
\ No newline at end of file

```

2024-06-07 20:08 UTC, ReenigneArcher commented on docs/images/submission.png
This image looks identical to the `approver_guide.png`

2024-06-09 15:16 UTC, jjnether commented on docs/images/submission.png
Oops, yeah deleted the duplicate

2024-06-09 16:50 UTC, merged